/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MatrixScript */

#ifndef _Included_MatrixScript
#define _Included_MatrixScript
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MatrixScript
 * Method:    calculateString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MatrixScript_calculateString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
